{{- if .Values.rbac.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "fluentd-kube-elastic.fullname" . }}
  labels:
    {{- include "fluentd-kube-elastic.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "fluentd-kube-elastic.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "fluentd-kube-elastic.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}