{{- if eq (lower .Values.kind) "daemonset" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "fluentd-kube-elastic.fullname" . }}
  labels:
    {{- include "fluentd-kube-elastic.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "fluentd-kube-elastic.podSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- include "fluentd-kube-elastic.podAnnotations" . | nindent 8 }}
      labels:
        {{- include "fluentd-kube-elastic.podSelectorLabels" . | nindent 8 }}
    spec:
      {{- include "fluentd-kube-elastic.podSpec" . | nindent 6 }}
{{- end }}