{{- if not .Values.conf.elasticsearch.passwordSecret }}
{{ $currentScope := .}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "fluentd-kube-elastic.elasticsearch-secret" . }}
  labels:
    {{- include "fluentd-kube-elastic.labels" . | nindent 4 }}
data:
  ELASTICSEARCH_USER: {{ (.Values.conf.elasticsearch.user | required "user or passwordSecret should be defined!") | b64enc }}
  ELASTICSEARCH_PASSWORD: {{ (.Values.conf.elasticsearch.password | required "password or passwordSecret should be defined!") | b64enc }}
{{- end }}
