{{- if .Values.conf.elasticsearch.auth.enabled }}
{{- if and (.Values.conf.elasticsearch.auth.password) (.Values.conf.elasticsearch.auth.passwordSecret) }}
{{ fail "Both of auth.password and auth.passwordSecret could not be provided! Please choose only one of them." }}
{{- end }}

{{- if not .Values.conf.elasticsearch.auth.passwordSecret }}
{{ $currentScope := .}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "fluentd-kube-elastic.elasticsearch-secret" . }}
  labels:
    {{- include "fluentd-kube-elastic.labels" . | nindent 4 }}
data:
  ELASTICSEARCH_USER: {{ (.Values.conf.elasticsearch.auth.user | required "auth.enabled is true, auth.user or auth.passwordSecret should be defined!") | b64enc | quote }}
  ELASTICSEARCH_PASSWORD: {{ (.Values.conf.elasticsearch.auth.password | required "auth.enabled is true, auth.password or auth.passwordSecret should be defined!") | b64enc | quote }}
{{- end }}
{{- end }}
