kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "fluentd-kube-elastic.fluentd-cm" . }}
  labels:
    {{- include "fluentd-kube-elastic.labels" . | nindent 4 }}
data:
  fluent.conf: |
    <system>
      log_level {{ .Values.conf.logLevel | required "logLevel must be defined" }}
    </system>  
    @include config.d/*.conf