{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentd-kube-elastic.serviceAccountName" . }}
  labels:
    {{- include "fluentd-kube-elastic.labels" . | nindent 4 }}
  {{- with .Values.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
